noremap <silent> n j
noremap <silent> e k
noremap <silent> i l
noremap <silent> l u
noremap <silent> u i
noremap <silent> s d
noremap <silent> d g
noremap <silent> k n
noremap <silent> K N
noremap <silent> d s
